### ISSUE TITLE
How best to configure 

### ISSUE THREAD

**Issue by gavD** [go-graphite/carbon-clickhouse#144]
Hello, we (Telemetry team at HMRC) are using carbon-clickhouse 0.11.6 on our digital tax platform and we have some questions.

Our situation
--

99.9% of the time, the chunks of metrics data entering our platform are ingested by carbon-clickhouse in <1s and everything works brilliantly.

However, we have observed that every 6 months, we get a spate of chunks of data that for some reason carbon-clickhouse or clickhouse itself takes >60s to ingest. The result of this was that our Clickhouse ingest ground to a half in 5 of our 6 nodes.

Having inspected these files, I cannot find anything odd about them; it is not a mere function of their size and there's nothing obviously odd in the metrics.

Our mitigation
--

Initially, we moved the stuck .lz4 files out of the way; this unstuck the ingest.

We then increased our timeout to 3 minutes. _(99.9% of the time our data comes nowhere near this, 99.9% of the time it's <1s to ingest_).

This increase allowed us to ingest the affected .lz4 files.

Our configuration
--

here is what I believe to be the relavant config; I've removed sensitive info

```toml
max-cpu = 2

[data]
# Folder for buffering received data
path = "/data/carbon-clickhouse/"
# Rotate (and upload) file interval.
# Minimize chunk-interval for minimize lag between point receive and store
chunk-interval = "1s"
# Auto-increase chunk interval if the number of unprocessed files is grown
# Sample, set chunk interval to 10 if unhandled files count >= 5 and set to 60s if unhandled files count >= 20:
chunk-auto-interval = "5:10s,20:60s"
# Compression algorithm to use when storing temporary files.
# Might be useful to reduce space usage when Clickhouse is unavailable for an extended period of time.
# Currently supported: none, lz4
compression = "lz4"
# Compression level to use.
# For "lz4" 0 means use normal LZ4, >=1 use LZ4HC with this depth (the higher - the better compression, but slower)
compression-level = 0

[upload.graphite]
type = "points"
table = "graphite.graphite"
threads = 2
url = "http://localhost:8123/"
timeout = "3m0s"

[upload.graphite_index]
type = "index"
table = "graphite.graphite_index"
threads = 2
url = "http://localhost:8123/"
timeout = "3m0s"
cache-ttl = "12h0m0s"
disable-daily-index = false

[udp]
enabled = false

[tcp]
listen = "localhost:2103"
enabled = true
drop-future = "0s"
drop-past = "0s"

[pickle]
enabled = false

[grpc]
enabled = false

[prometheus]
enabled = false

```

Our questions
--

1. Is it worth us upgrading to 0.11.7 - would that help with this intermittent issue?
2. Are there any risks with us having increased the timeout from 1m to 3m
3. What is the effect of `chunk-auto-interval` being set to "5:10s,20:60s"? My understanding is that the more chunks we have, the more carbon-clickhouse will slow the ingest cadence down to give it time ingest the larger chunks. However, if 60s is the cap, should that be raised to match our timeout? As much detail as you could give here would be so helpful to my team and I.
4. Can you suggest anything that may be causing us to have these rare incidents?

We really really appreciate any guidance you can offer us!
